### ISSUE TITLE
Last two myst-launcher-x64.msi releases detected as Trojan-PSW.Win32.Greedy.cpe

### ISSUE THREAD

**Issue by AjmalShajahan** [mysteriumnetwork/myst-launcher#113]
Hi, the last two stable releases https://github.com/mysteriumnetwork/myst-launcher/releases/tag/1.0.47 and https://github.com/mysteriumnetwork/myst-launcher/releases/tag/1.0.48 are detected as Trojan-PSW.Win32.Greedy.cpe by Kaspersky AV, ZoneAlarm detects v1.0.48.msi

VirusTotal:
myst-launcher-x64-v1.0.47.msi https://www.virustotal.com/gui/file/5a6187362562baff80a01aabaca1b609a82b5c279d35f890aa12972a0f5f38cb
myst-launcher-x64-v1.0.48.msi https://www.virustotal.com/gui/file/26dad3b3051a6b8dd14148a66abf2d8482764008c818aae04ed10703cbd274cd/detection

**Comment by Zensey** [comment]
Hi @AjmalShajahan 
Thanks for reporting this.

I not sure that all reports are 100% reliable there
![image](https://github.com/mysteriumnetwork/myst-launcher/assets/769152/c83d5f47-2076-4ef3-99e6-b741023d9321)

but many of of reports deserve to be addressed.

Summary:
https://www.virustotal.com/gui/file/93c67261d5cf69c14a9009eea56ab6b970cd82f2caefea1b5920846316a8a28c/behavior

**Comment by Zensey** [comment]
https://github.com/mysteriumnetwork/myst-launcher/releases/tag/1.0.49

**Comment by AjmalShajahan** [comment]
> Hi @AjmalShajahan Thanks for reporting this.
> 
> I not sure that all reports are 100% reliable there 
> 
> ![image](https://private-user-images.githubusercontent.com/769152/335234969-c83d5f47-2076-4ef3-99e6-b741023d9321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTIwNDIsIm5iZiI6MTcxNzM5MTc0MiwicGF0aCI6Ii83NjkxNTIvMzM1MjM0OTY5LWM4M2Q1ZjQ3LTIwNzYtNGVmMy05OWU2LWI3NDEwMjNkOTMyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwNTE1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmI3NThkNDI2MTYyMDFhZTAxMjZkYjQ0MmFhNzhiM2M2MDE0NGI5NDcxZmU0YjM4YjljMmJjYTExNTBhOTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9cbPYJv8BAr9c-kM_Lr7jr7BO4KF8S4FWL-PIgjiYVw)
> 
> but many of of reports deserve to be addressed.
> 
> Summary: [virustotal.com/gui/file/93c67261d5cf69c14a9009eea56ab6b970cd82f2caefea1b5920846316a8a28c/behavior](https://www.virustotal.com/gui/file/93c67261d5cf69c14a9009eea56ab6b970cd82f2caefea1b5920846316a8a28c/behavior)

Yeah thanks for looking into it, I just wanted it to be known so that it could be fixed in further updates.
