### ISSUE TITLE
"Please Enable virtualization in BIOS" error while virtuallization is enabled

### ISSUE THREAD

**Issue by danielkp1234** [mysteriumnetwork/myst-launcher#31]
So I keep getting this message
![image](https://user-images.githubusercontent.com/19412591/129784073-99199c37-3f3c-462a-86a8-82afeb4d2a49.png)

But virtualization is already enabled 
![image](https://user-images.githubusercontent.com/19412591/129784140-262a28d8-4549-4e54-9f7b-1ae8eab648b1.png)

I have tried on two different pcs and I get the same result. On one of them virtualization also shows as enabled in the CPU page in task manager

**Comment by Zensey** [comment]
Hi @danielkp1234 

Looks like a system configuration issue.
Could you please run the following diagnostic commands in PowerShell (Admin mode) and copy the output:

(gcim Win32_ComputerSystem).HypervisorPresent
(gcim win32_processor).VirtualizationFirmwareEnabled
(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online).State
Get-Service vmcompute
bcdedit

Use bcdedit to know the current state of hypervisor.
If hypervisorlaunchtype is "off", then change it with `bcdedit /set hypervisorlaunchtype auto` (reboot is required).

**Comment by danielkp1234** [comment]
@Zensey 
![image](https://user-images.githubusercontent.com/19412591/130240225-1c0d186c-aea2-4244-8003-01d15274789c.png)
I cant find any hypervisorlaunchtype

**Comment by Zensey** [comment]
@danielkp1234 
What version of Windows are you using ? Run `systeminfo`

**Comment by danielkp1234** [comment]
@Zensey 
![image](https://user-images.githubusercontent.com/19412591/130249309-a918f9d5-7cc2-4de4-87e3-c1ce554e9af4.png)

**Comment by Zensey** [comment]
@danielkp1234
It seams like the Virtual Machine Platform is disabled on your machine.

Please run the following commands in PowerShell (Admin mode):

dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /norestart
bcdedit /set hypervisorlaunchtype auto

And then reboot your system.

**Comment by danielkp1234** [comment]
That's looks to have fixed it on both of my pc. Thanks but weird shouldn't the installer automatically do this?

**Comment by Zensey** [comment]
@danielkp1234

Yes, It should.
I'll take this into account.
Thanks.

**Comment by Zensey** [comment]
Resolved in ver. 1.0.4
