### ISSUE TITLE
 Improve UX of installation process

### ISSUE THREAD

**Issue by Zensey** [mysteriumnetwork/myst-launcher#56]
- [x] Minimize interactions during installation (requests of Administrator rights)
- [x] Discover docker and set environment variables for child on installation finish
- [x] Correct pull image operation timeout
- [x] Set shield icon to button when privilege elevation is expected
- [ ] Add hyper-v installation helper for Windows home

**Comment by Donatas-MN** [comment]
@lusine-h Did you have a chance to test this?

**Comment by lusine-h** [comment]
yes, testing is done and it works as expected
