### ISSUE TITLE
"Click yes to sing out from the current session to finish the installation" loop while installing

### ISSUE THREAD

**Issue by Moldytzu** [mysteriumnetwork/myst-launcher#60]
I'm at the final step of instalation ("Check group membership") and then a message box like this appeared. I click yes then it signs me out, and then the launcher starts automatically and then asks me to click install. It goes thru each step again but faster but at the end the same message box appears.
![image](https://user-images.githubusercontent.com/40271862/151664736-834a8972-cc0a-4fa4-8d5f-d5c3040703b4.png)

**Comment by Moldytzu** [comment]
UPDATE: I saw that docker didn't install and then I tried to install it manually. I got some errors about Server and Workstation services not being enabled and then I enabled it.

**Comment by Zensey** [comment]
@Moldytzu 
Hi Alex 
Could you tell me the version and build of this particular Windows setup.
I'd like to reproduce this situation.

**Comment by Moldytzu** [comment]
I used the lastest version from the releases tab

**Comment by Zensey** [comment]
@Moldytzu 
I ment the Windows edition / version / build.
