### ISSUE TITLE
WinHTTP Web proxy taking a lot of system resources

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/myst-launcher#67]
Version: 1.0.34

WinHTTP Web proxy taking a lot of system resources when node is running

![image](https://user-images.githubusercontent.com/91055712/190384011-93bb50f6-911a-4600-9a81-998edc1facb3.png)

**Comment by Zensey** [comment]
@Donatas-MN 
I think it is safe to disable this service.
https://www.techwalla.com/articles/how-to-disable-winhttp-web-proxy-auto-discovery
