### ISSUE TITLE
Add checkbox to enable Launcher start on Windows start

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/myst-launcher#69]
Tasks:
 - [ ] Change `Autostart launcher` --> `Start with Windows`
 - [ ] Make it selected by default
 - [ ] Verify it's working as expected

**Comment by kiraitachi** [comment]
Hi @Donatas-MN 

I just migrated my Linux VM Node to my actual Windows Server 2022 using the launcher and realized the "Autostart Launcher" is not working.

You can find more info here:

https://github.com/mysteriumnetwork/myst-launcher/issues/71

**Comment by kiraitachi** [comment]
As a workaround I created a task in Task Scheduler. For anyone trying to fix this, you can import the following xml onto your task scheduler.

`<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2022-09-25T00:39:54.4610818</Date>
    <Author>HYPERVSERV\Administrator</Author>
    <URI>\Mysterium Start at boot</URI>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <Enabled>true</Enabled>
      <Delay>PT1M</Delay>
    </BootTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-21-166260488-2096353984-3558904547-500</UserId>
      <LogonType>Password</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>false</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>"C:\Program Files\MystNodeLauncher\myst-launcher-amd64.exe"</Command>
    </Exec>
  </Actions>
</Task>`

Change values as you see fit. On this XML my machine name and user "administrator" are the default values.
