### ISSUE TITLE
Autostart Launcher Node Option not working on Windows Server

### ISSUE THREAD

**Issue by kiraitachi** [mysteriumnetwork/myst-launcher#71]
Describe the bug
I run Windows Server 2022 Datacenter version on my homelab server. I sometimes have a powercut because my kid decides to push the powerbutton. I realized that after rebooting the "Autostart Launcher" option is enabled in the launcher but still does not autostart with my Server. I have to manually start it.

To Reproduce

Shutdown or restart
No autostart happens
Go to Mysterium Launcher and start
Expected behavior
Expected that after reboots or shutdown, with option enabled "Autostart Launcher" it would actually automatically start the node.

Screenshots
![image](https://user-images.githubusercontent.com/40744673/191109848-70938931-bd82-40e8-9626-c548f6a24a19.png)

Environment (please complete the following information):

Node version: 1.17.3
OS: Windows Server 2022 Datacenter Edition
Running on Native Backend
![image](https://user-images.githubusercontent.com/40744673/191109830-d95ad540-d745-4714-8014-a208f1afeb90.png)

**Comment by Zensey** [comment]
@kiraitachi 
with the latest release 1.0.35 auto startup should work.
