### ISSUE TITLE
"Accept Terms and conditions" is shown every time when node is started

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/myst-launcher#73]
OS: Windows 11
Launcher: 1.0.34

I've completed registration and accepted Terms, but every time when Node starts again it asks again to agree:
![Screenshot 2022-09-20 105324](https://user-images.githubusercontent.com/91055712/191228112-f12f19c4-6eaf-4078-96a3-0be93ec1f077.png)

**Comment by Ayse-AK** [comment]
@Donatas-MN A task was already created for this I added your finds as well.

**Comment by Donatas-MN** [comment]
Thanks.
