### ISSUE TITLE
CLI-mode (native) launcher

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/myst-launcher#89]
Kryptex (potential partner) requested on the following options to manage nodes via CI:

- It should download the newest node version (if it's not already there and up-to-date);
- Run the node as child process;
- It should accept Ctrl+C and pass it on to the node for it to shut down gracefully.

**Comment by Zensey** [comment]
Fixed by https://github.com/mysteriumnetwork/myst-launcher/pull/90
