### ISSUE TITLE
Custom launcher for Kryptex #1 (including only vendor ID)

### ISSUE THREAD

**Issue by ZygintasBudrys** [mysteriumnetwork/myst-launcher#96]
As a Kryptex user I would like to have a customized launcher that would assign vandor ID to the node upon install so that it would be possible to track the number of users coming via Kryptex channel.

## UACs

1. Custom launcher is prepared for download
2. Vendor ID "Kryptex_IU" is assigned to the node during install.

**Comment by Zensey** [comment]
A build with Vendor ID
https://github.com/mysteriumnetwork/myst-launcher/releases/download/1.0.44-rc4
https://github.com/mysteriumnetwork/myst-launcher/releases/download/1.0.44-rc4/myst-launcher-kryptex-x64.msi
